---
# Project Information
site_name: FastExcerpt
site_author: Kevin Alex Zhang
site_description: Fast extraction of relevant excerpts for long-form text.

# Repository information
repo_name: k15z/fastexcerpt
repo_url: https://github.com/k15z/fastexcerpt
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2020 Kevin Alex Zhang

# Configuration
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
  language: en

# Footer
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/k15z
      name: k15z on GitHub

# Page tree
nav:
  - Home: index.md
  - Roadmap: roadmap.md
